#!/bin/bash

serverEndpoint="0.0.0.0"
sharedDirectory="dirA/dirB"
serverPublicDir=/dirA/dirB
destination=dirA/dirB
scheme="YOUR_SCHEME"

function updateWorkspaceConf() {
    serverWorkspaceConf=$serverPublicDir/$destination
    echo "+ serverWorkspaceConf=$serverWorkspaceConf"

    if [[ ! -f $PWD/release-notes.md ]]
    then
        echo "+ release-notes.md file does not exist"
        echo "+ Creating release-notes.md ..."
        {
            echo "### THE TITLE OF YOUR TASK"
            echo "* **Author**: [YOUR_NAME]"
            echo "* **Branch**: [YOUR_WORKING_BRANCH]"
            echo "* **Server**: private/public IP address (http://0.0.0.0:3000) or N/A"
            echo "* **Artifact Configurations**:"
            echo "  - Plugin version: 1.2.3"
            echo "  - My custom config: ..."
            echo "  - ..."
            echo "* **This release includes**:"
            echo "  - Fixed app crashed"
            echo "  - Bug fixes"
            echo "  - Performance improvements"
            echo "  - ..." 
        } >> $PWD/release-notes.md
        echo "+ release-notes.md file has been created"
    fi

    if [[ -f $PWD/release-notes.md ]]
    then
        echo "+ The following content is your release notes, let check it out and make some changes if you have your own update"
        echo ""
        echo "--------------------------------------------------"
        cat $PWD/release-notes.md
        echo "--------------------------------------------------"
        echo ""
    fi

    cp $PWD/release-notes.md $serverWorkspaceConf/release-notes.md
    echo "+ cp $PWD/release-notes.md $serverWorkspaceConf/release-notes.md"
}

if [[ -d "$serverPublicDir" ]]
then
    echo "+ $serverPublicDir exists on your file system"
    echo "+ CONNECTED TO smb://$serverEndpoint/$sharedDirectory"
    updateWorkspaceConf
else
    echo "+ $serverPublicDir does not exists on your file system"
    echo "+ PLEASE CONNECT TO YOUR SERVER BEFORE YOU DO MORE LATER STEPS"
fi
